[build]
  base = "/"
  publish = "public/"
  command = "gatsby build --verbose"

[build.environment]
  ENABLE_GATSBY_REFRESH_ENDPOINT="true"
  PROJECT_NAME="John Hodge"
  BACKGROUND_COLOR="#1F2023"
  THEME_COLOR="#1F2023"
  TWITTER="hodge_etc"
  TWITTERID="376312987"
  INSTAGRAM="cafehodge"
  GITHUB="johnhodge"