[build]
  base = "/"
  publish = "public/"
  command = "gatsby build"

[context.branch-deploy.environment]
  CONTENTFUL_ENVIRONMENT="issues-54"

[context.deploy-preview.environment]
  CONTENTFUL_ENVIRONMENT="staging"