[build]
  base = "website/"
  publish = "public/"
  command = "gatsby build --verbose"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
